### ISSUE TITLE
1.0.75.483.g7ff4a0dc broke Toastify global shortcuts

### ISSUE THREAD

**Issue by c-lgrant** [nachmore/toastify#16]
https://community.spotify.com/t5/Desktop-Windows/1-0-75-483-g7ff4a0dc-broke-Toastify-global-shortcuts/td-p/4403231

**Comment by aleab** [comment]
Have a look at [this](https://github.com/aleab/toastify)! The version of that fork still doesn't work with the current version of Spotify, but I'm planning on releasing a fix this week.

**Comment by MicahArmantrout** [comment]
https://github.com/MicahArmantrout/toastify I created a branch and fixed the issue check it out

**Comment by aleab** [comment]
@MicahArmantrout, nice!
However, your solution is surely gonna fail sometimes and might not work for everyone. The *"Chrome_WidgetWin_0"* class name might or might not be used by every application that makes use of CEF ([here](https://en.wikipedia.org/wiki/Chromium_Embedded_Framework#Applications_using_CEF)'s a list of known applications that use it) and even the latest release of Spotify itself uses several different top-level active "windows" with that class name, so you can't always be sure you are getting the right window.

![Spy++](https://vgy.me/LeNQUZ.png)

At the very least you should also check for the window title ("Spotify"), but even then it will only work if Spotify is not reproducing anything, since the window title is changed to the current song if it is.

**Comment by MicahArmantrout** [comment]
Good points it was a stab and I definitely don't write in this realm often I will work with it some more

**Comment by goldstar2154** [comment]
@MicahArmantrout this is bad coding style, replace whole method with

```
private static IntPtr GetSpotify()
{
    var procs = System.Diagnostics.Process.GetProcessesByName("Spotify");

    foreach (var proc in procs)
    {
        if (proc.MainWindowHandle != IntPtr.Zero)
            return proc.MainWindowHandle;
    }

    return IntPtr.Zero;
}
```

**Comment by aleab** [comment]
@goldstar2154, what exactly is bad about using Windows APIs?
I'm not sure, but I think your method always fails if Spotify is minimized (to the taskbar or to the tray), since `MainWindowHandle` will return Zero (at least, I remember it doing that during my tests).
Also, remember that there's no such thing as "main window" in Windows, so the value returned by `MainWindowHandle` is just a guess (see [this](https://stackoverflow.com/questions/4727023/why-cant-get-the-main-window-handle-for-a-started-process)) and it might not actually return the expected window.

**Comment by goldstar2154** [comment]
@aleab it is not bad using WinAPI. It's bad style directly search window by name. Spotify change window's name and app doesnt work. Much better look for process and for this process main window.
MainWindowHandle mean toplevel window (doesnt matter have it focus or no). Thats window we need to send command :) You can test this method with your fork of toastify.

**Comment by aleab** [comment]
@goldstar2154, I tested it myself days ago and I'm already using it in part as a solution to this issue.

My point was that using **only** `MainWindowHandle` to get the "main window" of a process might be unreliable, since, as I said, it might return the wrong handle in certain scenarios or no handle at all, even if the process does have a window.

You can test your method and see if it returns the right handle when Spotify is minimized to the taskbar and then when it's minimized to the tray.
As I said, I remember `MainWindowHandle` returning a wrong handle in one of those cases.

**Comment by MicahArmantrout** [comment]
When it is minimized to the systray there is the handle is zero

**Comment by aleab** [comment]
@MicahArmantrout, an `IntPtr.Zero` handle is not a valid window handle at all.

**Comment by MicahArmantrout** [comment]
clearly ...

**Comment by goldstar2154** [comment]
@aleab you're right, this is uncomplete solution.
But searching by name is bad design too (because there are more than 1 window with name 'Chrome_WidgetWin_0')
When spotify minimized (tray or taskbar) main window also exists and GetSpotify() return valid HWND
(because when window minimized to tray it still exists in memory)
Problem that this window is not that window we need)
![scr1](https://user-images.githubusercontent.com/25493715/37116438-60aa4954-225f-11e8-830f-ddb041ee5704.png)

Our needed window is not child of top-window, but owned by parent. Now i need to test enumerating by owner, maybe it can helps)

**Comment by goldstar2154** [comment]
@aleab how about this solution?
```
private static IntPtr GetSpotify()
{
    var procs = System.Diagnostics.Process.GetProcessesByName("Spotify");

    foreach (var proc in procs)
    {
        if (proc.MainWindowHandle != IntPtr.Zero)
        {
            IntPtr owned_wnd = proc.MainWindowHandle;
            Win32.EnumWindows(delegate (IntPtr hWnd, IntPtr lParam)
            {
                if (Win32.GetWindow(hWnd, Win32.Constants.GW_OWNER) == lParam)
                {
                    owned_wnd = hWnd;
                    return false;
                }

                return true;
            },
            proc.MainWindowHandle);

        return owned_wnd;
    }
}
```

**Comment by goldstar2154** [comment]
@aleab you're right... If spotify minimized there are no `MainWindowHandle` . And i dont know proper solution for finding spotify main window. I test all windows from spotify's processes and all windows with name "Chrome_Widget_0" can accept WM_APPCOMMAND messages, except window with caption
![scr1](https://user-images.githubusercontent.com/25493715/37122345-43b7cd46-2271-11e8-8b62-1c8737625df5.png)

**Comment by goldstar2154** [comment]
As i see toastify uses WM_APPCOMMAND  with some multimedia keys (like Next/Prev/Pause...). Maybe we can try use `SendInput()` instead of `SendMessage()`. Spotify also handle these keys.

**Comment by MicahArmantrout** [comment]
What if we were able to map keys to Next / Prev  ect ... doesn't spotify listen for media keys ?

**Comment by aleab** [comment]
WM_APPCOMMAND works fine in my fork, but not for VOLUME_UP/VOLUME_DOWN/VOLUME_MUTE; be sure to use `PostMessage` instead of `SendMessage`. For volume control the only solution is to send a global media key event, for example using `SendInput` or `keybd_event`.

To clarify, sending media key events to change the volume, changes the global volume in the Windows Volume Mixer, not in Spotify, unfortunately.

Also, sending Spotify's keyboard shortcuts (like *"Shift+Right"* for *Seek Forward*) with `SendMessage` or `PostMessage` doesn't work, unfortunately (at least it didn't when I tried a couple of days ago).

**Comment by goldstar2154** [comment]
@MicahArmantrout think this can work)
@aleab SendMessage & PostMessage need to be sent directly in control that can handle message (for example with notepad.exe you need send WM_CHAR directly to edit-control not to the main window)  I have no idea what controls are in WebView... And most WM_ messages require focus.
Also there is another way - injecting thread input into spotify's processes with `AttachThreadInput()`

**Comment by aleab** [comment]
@goldstar2154, I think you are a bit confused on `SendMessage`/`PostMessage` or I didn't understand what you meant.

From the msdn documentation of [`PostMessage`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms644944.aspx):
> Places (posts) a message in the message queue associated with the thread that created the specified window and returns without waiting for the thread to process the message.

```c++
BOOL WINAPI PostMessage(
  _In_opt_ HWND   hWnd,
  _In_     UINT   Msg,
  _In_     WPARAM wParam,
  _In_     LPARAM lParam
);
```
> *hWnd* [in, optional]
>A handle to the window whose window procedure is to receive the message.
>
> *Msg* [in]
>The message to be posted.
>
>*wParam* [in]
>Additional message-specific information.
>
> *lParam* [in]
>Additional message-specific information.

There's no mention of controls anywhere. You just need to send it to the window.

**Comment by aleab** [comment]
I quickly read the documentation of `AttachThreadInput` and the following part doesn't really convices me that it's possible:

> By using the AttachThreadInput function, a thread can attach its input processing mechanism to another thread. Keyboard and mouse events received by both threads are processed **by the thread specified by the idAttachTo parameter** until the threads are detached.

> *idAttach* [in]
> The identifier of the thread to be attached to another thread. The thread to be attached cannot be a system thread.
>
>*idAttachTo* [in]
> The identifier of the thread to which idAttach will be attached. This thread cannot be a system thread.

If we attach Toastify's thread to Spotify's, any mouse and keyboard event intended only for Toastify (in the Settings window, for example) won't be handled by it, but rather by Spotify. Or did I interpret that part wrong?

**Comment by goldstar2154** [comment]
@aleab in Windows each control is a window too, so if you need send WM_CHAR to notepad you need send WM_CHAR to edit-control. Look
![scr2](https://user-images.githubusercontent.com/25493715/37125434-9f11d1b2-227d-11e8-8d1d-88d949e0b3b7.png)
```
UINT ScanCode = MapVirtualKey(VK_SPACE, 0);
LPARAM lParam = ScanCode << 16;
lParam |= 1;

HWND notepad = FindWindow(_T("Notepad"), NULL);             // red window
HWND edit = FindWindowEx(notepad, NULL, _T("Edit"), NULL);  // blue window
    
PostMessage(edit, WM_KEYDOWN, VK_SPACE, (lParam));  // ok, VK_SPACE inserted

PostMessage(notepad, WM_KEYDOWN, VK_SPACE, (lParam)); // not ok
```

I dont know how it works in webview, but we need send messages to window that can handle them

**Comment by aleab** [comment]
Oh, I understand what you meant now! You are right!
That doesn't really matter, though, since we already know that the main window (the *"Chrome_WidgetWin_0"* with the non-empty title) does handle certain app messages. It handles correctly `APPCOMMAND_MEDIA_PLAY_PAUSE`, `APPCOMMAND_MEDIA_NEXTTRACK`, `APPCOMMAND_MEDIA_PREVIOUSTRACK`, `APPCOMMAND_MEDIA_FAST_FORWARD` and `APPCOMMAND_MEDIA_REWIND` commands, but it does not handle `APPCOMMAND_VOLUME_UP`, `APPCOMMAND_VOLUME_DOWN` nor `APPCOMMAND_VOLUME_MUTE`.
